name: Generate pacman animation

on:
  # Roda a cada 12 horas
  schedule:
    - cron: "0 */12 * * *"
  
  # Permite que você rode manualmente pela aba Actions
  workflow_dispatch:
  
  # Roda quando há um push para o branch main
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Gera os arquivos .svg do gráfico de contribuição
      - name: generate pacman-contribution-graph
        uses: aboronon/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          
      # Envia os arquivos gerados para o branch 'output'
      - name: push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
